### ISSUE TITLE
Jekyll?

### ISSUE THREAD

**Issue by eonist** [JonathanSpeek/spacegrid_ghost_theme#1]
This is 👌Saw you on the PH🚀 

Why not Jekyll though 😊

**Comment by JonathanSpeek** [comment]
@eonist Looking to make a Jekyll theme soon (won't be too much work).

**Comment by eonist** [comment]
@JonathanSpeek Is ghost bigger than Jekyll? I don't get why there is so few good designs for Jekyll.

**Comment by JonathanSpeek** [comment]
@eonist I'd say Jekyll is more popular. Their integration with Github's pages feature would lead me to believe it's more popular, anyway. I can't speak to the designs, hopefully I can make a simple and clean one for people to use.

**Comment by eonist** [comment]
I mean it takes 30sec to make a jekyll blog: https://vimeo.com/154566844 <- my video

**Comment by eonist** [comment]
If you could add a similar repo it would take 30 sec to make A spacegrid site.
